all: affichage factorielle portee flottant

affichage: affichage.c 
	gcc affichage.c -o affichage

factorielle: factorielle.c 
	gcc factorielle.c -o factorielle

portee: portee.c
	gcc portee.c -o portee

flottant: flottant.c
	gcc flottant.c -o flottant

clean:
	rm -f *.o
	rm -f affichage